# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('web', models.TextField()),
                ('address', models.TextField()),
                ('zipcode', models.IntegerField()),
                ('tipo', models.TextField()),
                ('categoria', models.TextField()),
                ('subcategoria', models.TextField()),
                ('comentario', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='imagen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteles.Imagenes'),
        ),
    ]
