# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0003_auto_20160512_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='tipo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hotelsuser',
            name='user',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paguser',
            name='color',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paguser',
            name='size',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paguser',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paguser',
            name='user',
            field=models.TextField(),
        ),
    ]
