# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0005_auto_20160514_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='paguser',
            name='nombrepag',
            field=models.TextField(default=''),
        ),
    ]
