# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0006_paguser_nombrepag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paguser',
            name='user',
            field=models.TextField(default=''),
        ),
    ]
