# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0007_auto_20160516_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paguser',
            name='nombrepag',
        ),
    ]
