# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0008_remove_paguser_nombrepag'),
    ]

    operations = [
        migrations.AddField(
            model_name='paguser',
            name='npag',
            field=models.TextField(default=''),
        ),
    ]
