# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-17 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0009_paguser_npag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paguser',
            name='npag',
        ),
    ]
