# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0010_remove_paguser_npag'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
