# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0011_hotel_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='punt',
            field=models.IntegerField(default=0),
        ),
    ]
