# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0013_auto_20160518_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
