# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0015_remove_hotel_puntuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='body',
            field=models.TextField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='hotelsuser',
            name='user',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='paguser',
            name='color',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='paguser',
            name='size',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='paguser',
            name='title',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='paguser',
            name='user',
            field=models.CharField(default='', max_length=300),
        ),
    ]
