# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0016_auto_20160518_1311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comentario',
        ),
        migrations.RenameModel(
            old_name='HotelsUser',
            new_name='HotelesUsuario',
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='Imagen',
        ),
        migrations.RenameModel(
            old_name='PagUser',
            new_name='PaginaUsuario',
        ),
    ]
